### PR TITLE
Add ProgressBar to visualise progress in `Simulate()`

### PR DESCRIPTION
**Pull request by TobiasDuswald**
Added a ProgressBar such that one clearly sees the progress of the simulation. Example output:
```
ET = Elapsed Time; TR = Time Remaining
[######                                          ] 135 / 1000 ( ET:  1649, TR:10566)[ms]
```

Examples:
1. No output (default)
```
[bdm-1.3.4] (base) 
~/tmp/soma_clustering/build on  master! ⌚ 12:34:13
$ ./soma_clustering
number of cells in subvolume: 2360
average neighbors in subvolume: 28
correctness coefficient: 0.0157542
Simulation completed successfully!
```

2. Show Simulation step every 100 steps
```
[bdm-1.3.4] (base) 
~/tmp/soma_clustering/build on  master! ⌚ 12:36:10
$ ./soma_clustering  --inline-config '{ "bdm::Param": { "show_simulation_step": 100 } }' 
Time step: 0
Time step: 100
Time step: 200
Time step: 300
Time step: 400
Time step: 500
Time step: 600
Time step: 700
Time step: 800
Time step: 900
number of cells in subvolume: 2384
average neighbors in subvolume: 26
correctness coefficient: 0.0468571
Simulation completed successfully!
```

3. Use the progress bar
```
~/tmp/soma_clustering/build on  master! ⌚ 12:34:29
$ ./soma_clustering  --inline-config '{ "bdm::Param": { "use_progress_bar": true } }'

ET = Elapsed Time; TR = Time Remaining
[##################################################] 1000 / 1000 ( ET: 11988, TR:    0)[ms]
number of cells in subvolume: 2456
average neighbors in subvolume: 26
correctness coefficient: 0.026382
Simulation completed successfully!
```

### CODE REVIEW

**Comment by FonsRademakers** [comment]
Hi Tobias,

    very nice to have this progress bar. 
Could we implement a bit friendlier command line argument parsing like:

./soma_clustering —show_simulation_step=100

Instead of
 ./soma_clustering  --inline-config '{ "bdm::Param": { "show_simulation_step": 100 } }'
Where unknown arguments are internally being transformed to an inline-config string. This makes command line arguments much more user friendly. 

Thanks, Fons.

**Comment by TobiasDuswald** [comment]
> Hi Tobias, very nice to have this progress bar. Could we implement a bit friendlier command line argument parsing like: ./soma_clustering —show_simulation_step=100 Instead of ./soma_clustering --inline-config '{ "bdm::Param": { "show_simulation_step": 100 } }' Where unknown arguments are internally being transformed to an inline-config string. This makes command line arguments much more user friendly. Thanks, Fons.
> […](#)

**Comment by TobiasDuswald** [comment]
> [...] Could we implement a bit friendlier command line argument parsing [...]

Hi Fons,
I think you're raising a very valid point. It goes a little beyond this PR so I created a card on Trello such that we can return to it as soon as there is some free time. Thanks for pointing it out!

**Comment by FonsRademakers** [comment]
Thanks for having created a Trello card.

Cheers,Fons.



> On 17 Dec 2021, at 13:58, Tobias Duswald ***@***.***> wrote:
> 
> 
> [...] Could we implement a bit friendlier command line argument parsing [...]
> 
> Hi Fons,
> I think you're raising a very valid point. It goes a little beyond this PR so I created a card on Trello such that we can return to it as soon as there is some free time. Thanks for pointing it out!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

--------------------------------------------------------------------------
Dr. Fons Rademakers      CERN - European Organization for Nuclear Research
Chief Research Officer   1211 Geneve 23, Switzerland
CERN openlab             Tel: +41227679248            Mobile: +41754113742
--------------------------------------------------------------------------

**Pull request merged**
