### PR TITLE
Modify stability condition and decay check

### PR DESCRIPTION
**Pull request by TobiasDuswald**
$$
( \frac{\partial }{\partial t} - D\ \nabla^2 + \lambda)\ u = 0, \ \ \ D, \lambda \in \mathbb{R}, 
$$

**Stability condition:**

Derived via von Neumann stability analysis (https://en.wikipedia.org/wiki/Von_Neumann_stability_analysis) 

$$
\left( \lambda + \frac{12 \cdot D}{h^2} \right) \Delta t \leq 2
$$

**Decay check:**

Derived by assuming positivity of u^n and demanding positivity of u^{n+1}

$$
1 - \left( \lambda + \frac{6 \cdot D} {h^2} \right) \Delta t \geq 0
$$

### CODE REVIEW

**Comment by nicogno** [comment]
I have double checked the proposals and got the same results. It makes sense to me to implement the suggested proposals as they are in the master branch.

**Review by nicogno — APPROVED** [review]
I have double checked the proposals and got the same results. It makes sense to me to implement the suggested proposals as they are in the master branch.

**Comment by TobiasDuswald** [comment]
**!** Failing sonar cloud can be ignored here. Coverage only.

**Comment by vasvav** [comment]
Hi Tobias & Nicolo, 
some quick comments on this topic:
1. As far as i understood the "old" implementation of the time-step check assumes a uniform spatial resolution in all directions. However this would work in general. What I mean. If the diffusion grid has different "spacings" on the grid (i.e., ΔΧ, ΔΥ, ΔΖ) then you should check first which is the smallest one and pick that, and then subsequently implement the verification test for: Δt <= 0.166666666666667 * (ΔΧ^2) / DiffCoeff
2. Now that i digested the purpose/role of the source (or sink) term in the above governing equation, then I see that it will play NO role in the stability, and therefore the critical time-step. All you need to do to confirm this, simply deactivate the diffusion by setting it zero and then run a simulation for your Diffusion grid with the "λ" parameter being non-zero only.
3. I would revise the comment above  if the source/sink parameter has any spatial heterogeneity, meaning if it is dependent on the x,y,z direction... This would make things more complicated, but I doubt we would encounter anything like that, right?
cheers

**Comment by nicogno** [comment]
> Hi Tobias & Nicolo, some quick comments on this topic:
> 
> 1. As far as i understood the "old" implementation of the time-step check assumes a uniform spatial resolution in all directions. However this would work in general. What I mean. If the diffusion grid has different "spacings" on the grid (i.e., ΔΧ, ΔΥ, ΔΖ) then you should check first which is the smallest one and pick that, and then subsequently implement the verification test for: Δt <= 0.166666666666667 * (ΔΧ^2) / DiffCoeff
> 2. Now that i digested the purpose/role of the source (or sink) term in the above governing equation, then I see that it will play NO role in the stability, and therefore the critical time-step. All you need to do to confirm this, simply deactivate the diffusion by setting it zero and then run a simulation for your Diffusion grid with the "λ" parameter being non-zero only.
> 3. I would revise the comment above  if the source/sink parameter has any spatial heterogeneity, meaning if it is dependent on the x,y,z direction... This would make things more complicated, but I doubt we would encounter anything like that, right?
>    cheers

Dear @vasvav thank you for your comments.

1. As of now, BioDynaMo doesn't support heterogeneous spatial discretisation along the 3 axes of reference, i.e. $\DeltaΧ \equiv \DeltaΥ \equiv \DeltaΖ$. Therefore the check for the smallest spacing, though reasonable in a general context, is not necessary at the moment (in my opinion).

2. The term $\lambda$ in the equation above indicates a decay rather than a sink (such as the oxygen uptake from a cell). Its purpose is to represent the process by which chemicals are degraded, either by other substances, or naturally (breaking down into smaller parts). With the old implementation

    * the stability criterion (Courant-Friedrichs-Lewy condition) didn't take into account this term
    * users were allowed to plug in whatever value for it, thus possibly causing overstepping situations (such that the concentration of a substance in a voxel could become < 0)

    The goal of this PR is to introduce additional checks such that those conditions (stability + concentration $\geq 0$) are always met.

3. I do agree with you. The decay parameter, in this first simple implementation, is intended as $\lambda \in \mathbb{R}$

**Comment by vasvav** [comment]
Thanks @TobiasDuswald and @nicogno for the explanation of the stability condition mathematical derivation.
All looks great and I confirm the validity of the code edits!

**Pull request merged**
