### PR TITLE
Param update

### PR DESCRIPTION
**Pull request by vasvav**
1. Improved a bit the wording and clarified some core parameters description.
2. Allowed a simulation and a development parameter to be read from the configuration file.
3. Reset the default value for the simulation time step to =1.
4. Reset the min/max bounds of the simulation domain so that it's centralised to origin (0,0,0).
5. Reset the max displacement parameter to 1% of the simulation domain size.

### CODE REVIEW

**Comment by nicogno** [comment]
@vasvav I would suggest running `make format-all` in your next commit to begin with, this should solve a few unsuccessful checks

**Comment by vasvav** [comment]
> @vasvav I would suggest running `make format-all` in your next commit to begin with, this should solve a few unsuccessful checks

many thanks for the tip @nicogno - I learned something new today ;) 
btw, how do you think we could proceed to fix these?

**Comment by vasvav** [comment]
Great job @nicogno 👍 many thanks fixing these issues

**Comment by LukasBreitwieser** [comment]
Thanks for your PR @vasvav!
I agree that some default values, naming, or grouping need improvement. Unfortunately, changing the default values of parameters has far-reaching effects, as can be seen by the failing unit tests. It breaks all simulations and tests which don’t explicitly set the changed parameter. Therefore, please verify the correctness of all demos and notebooks.

I would recommend systematically reviewing all parameters and discussing them to minimize the number of backward compatibility-breaking changes. Here are two examples.

First, I think it would be a good idea to replace `min_bound` and `max_bound` with, e.g., `simulation_space` that accepts different values for each dimension and does not enforce a cubic simulation space. The neighbor search indices already support a non-cubic simulation space.

Second, The maximum displacement parameter should be removed. It is only used in the default pair-wise force calculation and not anywhere else. This means that, for example, the chemotaxis behavior can move agents beyond `max_displacement`. If limiting the displacement is an important feature, then we should add an operation or behavior that enforces it for the whole simulation.

A minor comment: I noticed that many `\n` were removed from the comments. They were usually added to improve the readability of the generated API reference (https://biodynamo.github.io/api/structbdm_1_1Param.html). Please check the Doxygen output of your PR.

**Comment by TobiasDuswald** [comment]
Do we have any `changelog` in the repository? We should consider adding one with this PR such that we can document the effect on backward compatibility.

**Comment by LukasBreitwieser** [comment]
Good point Tobias. We created a document to inform users of breaking changes [1], but it has been forgotten. We should revive it.

I also checked the code base for the maximum displacement parameter and realized I was wrong in my previous statement about it being exclusively used in the force implementation itself. It is used in `Cell` and `NeuriteElement` and the mechanical interaction implementations on the GPU. 

[1] https://github.com/BioDynaMo/biodynamo/blob/master/doc/user_guide/changelog.md

**Pull request closed without merging**
